# AUTOGENERATED! DO NOT EDIT! File to edit: 01_cp.ipynb (unless otherwise specified).

__all__ = ['multinomial_coefficients', 'multinomial_combinations']

# Cell
def multinomial_coefficients(K):
    """
    Returns the multinomial coefficients

    - `K` - A list of $k_1, k_2...$
    """
    res, i = 1, sum(K)
    i0 = K.index(max(K))
    for a in K[:i0] + K[i0+1:]:
        for j in range(1,a+1):
            res *= i
            res //= j
            i -= 1
    return res

def multinomial_combinations(items):
    return set(permutations(items))