# AUTOGENERATED! DO NOT EDIT! File to edit: 00_utils.ipynb (unless otherwise specified).

__all__ = ['suppress_stdout', 'timing', 'browse_images']

# Cell
from time import time
from contextlib import contextmanager
import sys, os
import ipywidgets as wgt
from IPython.display import Image, display

# Cell
@contextmanager
def suppress_stdout():
    with open(os.devnull, "w") as devnull:
        old_stdout = sys.stdout
        sys.stdout = devnull
        try:
            yield
        finally:
            sys.stdout = old_stdout

# Cell
@contextmanager
def timing(description: str = 'Time') -> None:
    try:
        start = time()
        yield
    finally:
        ellapsed_time = time() - start
        print(f'{description}: {ellapsed_time}')


# Cell
def browse_images(paths):
    def view_image(image_path):
        display(Image(image_path))
    return wgt.interact(view_image, image_path=paths)