# AUTOGENERATED! DO NOT EDIT! File to edit: 00_utils.ipynb (unless otherwise specified).

__all__ = ['suppress_stdout']

# Cell
from time import time
from contextlib import contextmanager
import sys, os
import ipywidgets as wgt
from IPython.display import Image, display

# Cell
@contextmanager
def suppress_stdout():
    """Temporarily Suppress Console Output in Python
    src: http://thesmithfam.org/blog/2012/10/25/temporarily-suppress-console-output-in-python/
    Example
    -------
    print("Now you see it")
    with suppress_stdout():
        print("Now you don't")
    >>> Now you see it
    """
    with open(os.devnull, "w") as devnull:
        old_stdout = sys.stdout
        sys.stdout = devnull
        try:
            yield
        finally:
            sys.stdout = old_stdout